### ISSUE TITLE
bootstrap-project; unable to provide no bindings

### ISSUE THREAD

**Issue by garethahealy** [rht-labs/helm-charts#25]
When using the bootstrap-project, I was hoping I could use a simple values.yml like:
```
enabled: true
namespaces:
- name: bob
```

but this outputs:

```
---
# Source: cluster-bootstrap/charts/bootstrap-project/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: "bob"
---
# Source: cluster-bootstrap/charts/bootstrap-project/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummy-sa
  namespace: "labs-ci-cd"
---
# Source: cluster-bootstrap/charts/bootstrap-project/templates/bindings.yaml
apiVersion: v1
kind: List
metadata:
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
items:
```

I'd of expected it not to create a serviceaccount or list of bindings.

CC @springdo ; re: gchat
